# Generated by Django 2.0.8 on 2018-08-27 18:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Propuesta', 'Propuesta'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('En proceso', 'En proceso'), ('Completado', 'Completado')], default='En proceso', max_length=10)),
                ('tipo', models.CharField(choices=[('CATEDRA-Maestros', 'CATEDRA-Maestros'), ('HELP-Padres', 'HELP-Padres')], max_length=200)),
                ('taller_sugerido', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('fax', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('region_educativa', models.CharField(max_length=200)),
                ('distrito_escolar', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('Elemental', 'Elemental'), ('Superior', 'Superior'), ('Intermedio', 'Intermedio'), ('Segunda Unidad', 'Segunda Unidad')], default='Elemental', max_length=200)),
                ('tipo', models.CharField(choices=[('Regular', 'Regular'), ('Educacion Especial', 'Educacion Especial'), ('Pre-vocaiconal', 'Pre-vocacional'), ('Especializada', 'Especializada'), ('Vocacional', 'Vocacional')], default='Regular', max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('anotaciones', models.CharField(max_length=200)),
                ('hoja_de_visita', models.FileField(upload_to='registros/visitas/')),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destreza',
            fields=[
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CATEDRA.Escuela')),
                ('espanol', models.CharField(max_length=200)),
                ('matematicas', models.CharField(max_length=200)),
                ('ingles', models.CharField(max_length=200)),
                ('prioridad', models.CharField(max_length=200)),
                ('materia_prioridad', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CATEDRA.Escuela')),
                ('matricula_de_estudiantes', models.IntegerField(default=0)),
                ('maestros_de_espanol', models.IntegerField(default=0)),
                ('maestros_de_matematicas', models.IntegerField(default=0)),
                ('maestros_de_ingles', models.IntegerField(default=0)),
                ('maestros_de_ciencias', models.IntegerField(default=0)),
                ('maestros_otros', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CATEDRA.Escuela')),
                ('nombre_del_director', models.CharField(max_length=200)),
                ('estado_del_director', models.CharField(choices=[('En propiedad', 'En propiedad'), ('Interino', 'Interino')], default='En propiedad', max_length=200)),
                ('email_del_director', models.EmailField(max_length=254)),
                ('telefono_del_director', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('nombre_del_consejero', models.CharField(max_length=200)),
                ('email_del_consejero', models.EmailField(max_length=254)),
                ('telefono_del_consejero', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('nombre_del_trabajador_social', models.CharField(max_length=200)),
                ('email_del_trabajador_social', models.EmailField(max_length=254)),
                ('telefono_del_trabajador_social', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('nombre_del_requisante', models.CharField(max_length=200)),
                ('email_del_requisante', models.EmailField(max_length=254)),
                ('telefono_del_requisante', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('nombre_del_presidente_del_consejo_escolar', models.CharField(max_length=200)),
                ('telefono_del_presidente_del_consejo_escolar', models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')])),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CATEDRA.Escuela')),
                ('presupuesto_asignado', models.CharField(blank=True, choices=[('1290', '1290'), ('1290 B', '1290 B'), ('Titulo II', 'Titulo II')], max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='visita',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATEDRA.Escuela'),
        ),
        migrations.AddField(
            model_name='visita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escuela',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATEDRA.Escuela'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
