# Generated by Django 2.0.8 on 2018-08-28 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='direccion_fisica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='direccion_zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='grados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='municipio_escolar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='operacional',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=200),
        ),
        migrations.AddField(
            model_name='escuela',
            name='zona',
            field=models.CharField(choices=[('URBANA', 'URBANA'), ('RURAL', 'RURAL')], default='RURAL', max_length=200),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_10',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_11',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_12',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_9',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_SGE',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_SGI',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_SGS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_infant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_k',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_pk',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_pke',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_pkm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_toddler',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(choices=[('Elemental', 'Elemental'), ('Superior', 'Superior'), ('Intermedio', 'Intermedio'), ('Segunda Unidad', 'Segunda Unidad'), ('Todos los niveles', 'Todos los niveles')], default='Elemental', max_length=200),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email_del_director',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='estado_del_director',
            field=models.CharField(blank=True, choices=[('En propiedad', 'En propiedad'), ('Interino', 'Interino')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono_del_director',
            field=models.CharField(blank=True, default='(000) 000-0000', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
    ]
