# Generated by Django 2.0.8 on 2018-08-28 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0002_auto_20180828_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='destreza',
            name='espanol_avanzado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='espanol_basico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='espanol_prebasico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='espanol_proficiente',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='ingles_avanzado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='ingles_basico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='ingles_prebasico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='ingles_proficiente',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='matematicas_avanzado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='matematicas_basico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='matematicas_prebasico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='destreza',
            name='matematicas_proficiente',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='destreza',
            name='espanol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destreza',
            name='ingles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destreza',
            name='matematicas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destreza',
            name='materia_prioridad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destreza',
            name='prioridad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email_del_consejero',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email_del_requisante',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email_del_trabajador_social',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre_del_consejero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre_del_presidente_del_consejo_escolar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre_del_requisante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre_del_trabajador_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono_del_consejero',
            field=models.CharField(blank=True, default='(000) 000-0000', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono_del_presidente_del_consejo_escolar',
            field=models.CharField(blank=True, default='(000) 000-0000', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono_del_requisante',
            field=models.CharField(blank=True, default='(000) 000-0000', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono_del_trabajador_social',
            field=models.CharField(blank=True, default='(000) 000-0000', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
    ]
