# Generated by Django 2.0.8 on 2018-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0003_auto_20180828_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='nombre_del_director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
