# Generated by Django 2.0.8 on 2018-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0004_auto_20180828_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='matricula_de_estudiantes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
