# Generated by Django 2.0.8 on 2018-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0007_auto_20180905_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Vendedor', 'Vendedor')], default='Vendedor', max_length=200),
        ),
    ]
