# Generated by Django 2.0.8 on 2018-09-07 14:26

import CATEDRA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0008_auto_20180905_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADJUNTAS', 'ADJUNTAS'), ('AGUADA', 'AGUADA'), ('AGUADILLA', 'AGUADILLA'), ('AGUAS BUENAS', 'AGUAS BUENAS'), ('AGUAS BUENAS', 'AGUAS BUENAS'), ('ANASCO', 'ANASCO'), ('ARECIBO I', 'ARECIBO I'), ('ARECIBO II', 'ARECIBO II'), ('ARROYO', 'ARROYO'), ('BARCELONETA', 'BARCELONETA'), ('BARRANQUITAS', 'BARRANQUITAS'), ('BAYAMON I', 'BAYAMON I'), ('BAYAMON II', 'BAYAMON II'), ('BAYAMON III', 'BAYAMON III'), ('CABO ROJO', 'CABO ROJO'), ('CAGUAS I', 'CAGUAS I'), ('CAGUAS II', 'CAGUAS II'), ('CAMUY', 'CAMUY'), ('CANOVANAS', 'CANOVANAS'), ('CAROLINA I', 'CAROLINA I'), ('CAROLINA II', 'CAROLINA II'), ('CATANO', 'CATANO'), ('CAYEY', 'CAYEY'), ('CEIBA', 'CEIBA'), ('CIALES', 'CIALES'), ('CIDRA', 'CIDRA'), ('COAMO', 'COAMO'), ('COMERIO', 'COMERIO'), ('COROZAL', 'COROZAL'), ('CULEBRA', 'CULEBRA'), ('DORADO', 'DORADO'), ('FAJARDO', 'FAJARDO'), ('FLORIDA', 'FLORIDA'), ('GUANICA', 'GUANICA'), ('GUAYAMA', 'GUAYAMA'), ('GUAYANILLA', 'GUAYANILLA'), ('GUAYNABO', 'GUAYNABO'), ('GURABO', 'GURABO'), ('HATILLO', 'HATILLO'), ('HORMIGUEROS', 'HORMIGUEROS'), ('HUMACAO', 'HUMACAO'), ('ISABELA', 'ISABELA'), ('JAYUYA', 'JAYUYA'), ('JUANA DIAZ', 'JUANA DIAZ'), ('JUNCOS', 'JUNCOS'), ('LAJAS', 'LAJAS'), ('LARES', 'LARES'), ('LAS MARIAS', 'LAS MARIAS'), ('LAS PIEDRAS', 'LAS PIEDRAS'), ('LOIZA', 'LOIZA'), ('LUQUILLO', 'LUQUILLO'), ('MANATI', 'MANATI'), ('MARICAO', 'MARICAO'), ('MAUNABO', 'MAUNABO'), ('MAYAGUEZ', 'MAYAGUEZ'), ('MOCA', 'MOCA'), ('MOROVIS', 'MOROVIS'), ('NAGUABO', 'NAGUABO'), ('NARANJITO', 'NARANJITO'), ('OROCOVIS', 'OROCOVIS'), ('PATILLAS', 'PATILLAS'), ('PEÑUELAS', 'PEÑUELAS'), ('PONCE I', 'PONCE I'), ('PONCE II', 'PONCE II'), ('PONCE III', 'PONCE III'), ('QUEBRADILLAS', 'QUEBRADILLAS'), ('RINCON', 'RINCON'), ('RIO GRANDE', 'RIO GRANDE'), ('SABANA GRANDE', 'SABANA GRANDE'), ('SALINAS', 'SALINAS'), ('SAN GERMAN', 'SAN GERMAN'), ('SAN JUAN I', 'SAN JUAN I'), ('SAN JUAN II', 'SAN JUAN II'), ('SAN JUAN III', 'SAN JUAN III'), ('SAN JUAN IV', 'SAN JUAN IV'), ('SAN JUAN V', 'SAN JUAN V'), ('SAN LORENZO', 'SAN LORENZO'), ('SAN SEBASTIAN', 'SAN SEBASTIAN'), ('SANTA ISABEL', 'SANTA ISABEL'), ('TOA ALTA', 'TOA ALTA'), ('TOA BAJA', 'TOA BAJA'), ('TRUJILLO ALTO', 'TRUJILLO ALTO'), ('UTUADO', 'UTUADO'), ('VEGA ALTA', 'VEGA ALTA'), ('VEGA BAJA', 'VEGA BAJA'), ('VIEQUES', 'VIEQUES'), ('VILLALBA', 'VILLALBA'), ('YABUCOA', 'YABUCOA'), ('YAUCO', 'YAUCO')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=CATEDRA.models.Empleado.upload_to),
        ),
        migrations.AddField(
            model_name='empleado',
            name='municipio',
            field=models.ManyToManyField(to='CATEDRA.Municipio'),
        ),
    ]
