# Generated by Django 2.0.8 on 2018-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0010_auto_20180910_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosDE',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('costo', models.IntegerField(default=0)),
            ],
        ),
    ]
