# Generated by Django 2.0.8 on 2018-09-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0012_ofrecimiento_propuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofrecimiento',
            name='participantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='municipio',
            field=models.ManyToManyField(blank=True, to='CATEDRA.Municipio'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='ofrecimientos',
            field=models.ManyToManyField(blank=True, to='CATEDRA.Ofrecimiento'),
        ),
    ]
