# Generated by Django 2.0.8 on 2018-09-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0013_auto_20180910_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='ofrecimientos',
        ),
        migrations.AddField(
            model_name='ofrecimiento',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CATEDRA.Propuesta'),
        ),
    ]
