# Generated by Django 2.0.8 on 2018-09-11 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0014_auto_20180910_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default='(000) 000-0000', max_length=200, validators=[django.core.validators.RegexValidator(message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
    ]
