# Generated by Django 2.0.8 on 2018-09-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0015_empleado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'CREADA'), ('EN EVALUACION', 'EN EVALUACION'), ('RECHAZADA', 'RECHAZADA'), ('NO INTERES', 'NO INTERES'), ('P.O. GENERADO', 'P.O. GENERADO')], default='CREADA', max_length=200),
        ),
    ]
