# Generated by Django 2.0.8 on 2018-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0016_auto_20180911_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofrecimiento',
            name='estado',
            field=models.CharField(choices=[('EN ENVALUACION', 'EN EVALUACION'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA')], default='EN EVALUACION', max_length=200),
        ),
    ]
