# Generated by Django 2.0.8 on 2018-09-24 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0019_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
