# Generated by Django 2.0.8 on 2018-10-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0020_purchaseorder_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('estrategia', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
    ]
