# Generated by Django 2.0.8 on 2018-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0022_propuesta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosde',
            name='tipo',
            field=models.CharField(choices=[('Colegio - Maestros', 'Colegio - Maestros'), ('Colegio - Padres', 'Colegio - Padres'), ('Publica - Maestros', 'Publica - Maestros'), ('Publica - Padres', 'Publica - Padres')], default='Publica - Maestros', max_length=200),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='tipo',
            field=models.CharField(choices=[('Colegio - Maestros', 'Colegio - Maestros'), ('Colegio - Padres', 'Colegio - Padres'), ('Publica - Maestros', 'Publica - Maestros'), ('Publica - Padres', 'Publica - Padres')], default='Maestros', max_length=200),
        ),
    ]
