# Generated by Django 2.0.8 on 2018-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEDRA', '0023_auto_20181012_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='necesidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
